#!/usr/bin/env bash
# devkit-compose.sh — Generate docker-compose.devkit.yml override for an instance/project
#
# Usage:
#   devkit-compose.sh generate <instance_name> <instance_index> <project_name> <output_dir>
#
# Reads registry.json to get service definitions, then generates a compose override
# file with instance-specific container names, ports, and network.

set -euo pipefail

REGISTRY_FILE="${CLAUDE_SKILL_DIR:-$(dirname "$0")/../skills/devkit}/registry.json"

generate_override() {
  local instance_name=$1
  local instance_index=$2
  local project_name=$3
  local output_dir=$4

  local base_port
  local range
  base_port=$(python3 -c "import json; print(json.load(open('$REGISTRY_FILE'))['base_port'])")
  range=$(python3 -c "import json; print(json.load(open('$REGISTRY_FILE'))['port_range_per_instance'])")

  local network_name="devkit-${instance_name}-net"
  local output_file="${output_dir}/docker-compose.devkit.yml"

  python3 -c "
import json, sys

registry = json.load(open('$REGISTRY_FILE'))
project = registry['projects'].get('$project_name')
if not project:
    print(f'Error: project $project_name not found in registry', file=sys.stderr)
    sys.exit(1)

instance_name = '$instance_name'
instance_index = $instance_index
base_port = $base_port
port_range = $range
network_name = '$network_name'

lines = []
lines.append('# Auto-generated by devkit for instance \"${instance_name}\"')
lines.append('# DO NOT EDIT — regenerated on devkit up')
lines.append('')
lines.append('services:')

for svc_name, svc_cfg in project['services'].items():
    offset = svc_cfg.get('port_offset', 0)
    internal_port = svc_cfg.get('internal_port', 0)
    container_name = f'devkit-{instance_name}-$project_name-{svc_name}'

    lines.append(f'  {svc_name}:')
    lines.append(f'    container_name: {container_name}')

    if offset > 0 and internal_port > 0:
        host_port = base_port + (instance_index * port_range) + offset
        lines.append(f'    ports:')
        lines.append(f'      - \"{host_port}:{internal_port}\"')

    lines.append('')

lines.append('networks:')
lines.append('  default:')
lines.append(f'    name: {network_name}')
lines.append(f'    external: true')
lines.append('')

with open('$output_file', 'w') as f:
    f.write('\n'.join(lines))

print(f'Generated {\"$output_file\"}')
print(f'Network: {network_name}')
print(f'Containers:')
for svc_name, svc_cfg in project['services'].items():
    offset = svc_cfg.get('port_offset', 0)
    internal_port = svc_cfg.get('internal_port', 0)
    container = f'devkit-{instance_name}-$project_name-{svc_name}'
    if offset > 0 and internal_port > 0:
        port = base_port + (instance_index * port_range) + offset
        print(f'  {container} → {port}:{internal_port}')
    else:
        print(f'  {container} (no exposed port)')
"
}

# Main dispatch
case "${1:-help}" in
  generate)
    generate_override \
      "${2:?instance_name required}" \
      "${3:?instance_index required}" \
      "${4:?project_name required}" \
      "${5:?output_dir required}"
    ;;
  help|*)
    echo "Usage: devkit-compose.sh generate <instance_name> <instance_index> <project_name> <output_dir>"
    echo ""
    echo "Generates docker-compose.devkit.yml override with instance-specific:"
    echo "  - Container names (devkit-{instance}-{project}-{service})"
    echo "  - Port mappings (base_port + index * range + offset)"
    echo "  - Network (devkit-{instance}-net)"
    exit 0
    ;;
esac
